
    public IOException(Throwable cause) {
        super(cause);
    }
}
